### PR TITLE
Fix: TODO This should just be one query.

### PR DESCRIPTION
**Pull request by shemgp**
Importing bulk extension csv from FreePBX 2.9, with fields renamed to have `findmefollow_`, resulted in error: `grptime does not have a default value`.  Here's the fix for it.

Note: I'm using `findmefollow_grptime` to determine if csv row has findmefollow values.

### CODE REVIEW

**Comment by tm1000** [comment]
Bulk Extensions is not supported in FreePBX 13. Furthermore Bulk Extensions does not reference any function in the class file (as it's too old it doesnt know about it).

The method you are editing was written explicitly for UCP where we need to change a single setting at a time. What you've done here with this is effectively broken UCP. When a user changes a single setting all other settings will be reset to zero/null/empty because they aren't defined. Hence the method called "addSettingById" is broken

Closing as this will break systems. Not sure how bulk extensions is calling this function but it's the wrong place, considering bulk extensions is depreciated in favor of bulk handler and FreePBX 13 is very late in it's life cycle I can only see this causing crashes/unknown issues when people save a single value from UCP and everything else is reset.

Functions:
https://github.com/FreePBX-ContributedModules/bulkextensions/blob/a9a9baa09dfebecff0a05105f7f57b7b83bc1c37/page.bulkextensions.php#L935
https://github.com/FreePBX/findmefollow/blob/release/13.0/functions.inc.php#L290

**Comment by shemgp** [comment]
The csv I'm using exported from "bulk extensions" from the old FreePBX 2.9, but I'm importing it using "Bulk Handler" in a new FreePBX 13 server, which I think uses that function.

The reason it doesn't import (without the patch) is because it was doing it one by one -- I mean column per column.  That's why I sent the patch to fix the TODO in that file :) 

So what do you recommend, create a new function with somewhat the same content to be used by "Bulk Handler"?

**Comment by tm1000** [comment]
Bulk Handler does not accept anything exported from Bulk Extensions or Bulk DIDs. To use Bulk Handler you must export from bulk handler and then import from bulk handler.

When you import a file from bulk extensions into bulk handler things will crash, as you have seen.

Your intent to fix how bulk handler functions is well intended however the method to which you are forcing bulk handler to work is wrong and furthermore modifying said "addSettingsById" without reviewing "addSettingById" only causes more issues.

Start with exporting from Bulk Handler and then importing that same file back into bulk handler if you wish to fix the functionality.

Another way to use your functionality without messing up the original functionality is to pull the original data before you update the new data. If a key isn't "set" then you simply pull the unset data from the original data. Therefore you can then change a single item or an array of items without messing up anything that is not set. This UCP would work AND so would bulk handler. You don't even have to check isset() as an array_merge (first parameter would be original data, second would be the new data) would work merging any new data on the right into the left array.

A change this big will also require Unit Tests and approval from our QA team (as is the norm now). If you wish to continue you are more than welcome.

**Comment by shemgp** [comment]
Hello,

I tried exporting using Bulk Handler and re-importing the exported file using the same module and it had an error like this:
screenshot from 2017-03-23 11-01-33

Here's my exported CSV: 
[extensions.csv.txt](https://github.com/FreePBX/findmefollow/files/863564/extensions.csv.txt)

I think it's because it's trying to import the fields one by one and fields that cannot be null are not being filled first or at the same time.

Thank you for your response.  

I'm willing to help this get fixed if you give me directions. All the best!

**Comment by shemgp** [comment]
> Another way to use your functionality without messing up the original functionality is to pull the original data before you update the new data. If a key isn't "set" then you simply pull the unset data from the original data. Therefore you can then change a single item or an array of items without messing up anything that is not set. This UCP would work AND so would bulk handler. You don't even have to check isset() as an array_merge (first parameter would be original data, second would be the new data) would work merging any new data on the right into the left array.

This might work if it's an update, but if it's an insert then I think it won't work. Could it not be that I just duplicate/work the function to a different name and call that function when importing from Bulk Handler?  That's because they're doing different things anyway.

**Pull request closed without merging**
